// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Gi3HehfGZK9ZewC0bcw0n9lh5fY7CEA',
    appId: '1:322956468011:web:86a0f35c1c0df38d792f6e',
    messagingSenderId: '322956468011',
    projectId: 'socialapp-5270d',
    authDomain: 'socialapp-5270d.firebaseapp.com',
    storageBucket: 'socialapp-5270d.firebasestorage.app',
    measurementId: 'G-182ETLZMCB',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs4fdz9ahQbGPIT0c0r6W7VylZQQO7wdg',
    appId: '1:322956468011:android:125176312cd6752e792f6e',
    messagingSenderId: '322956468011',
    projectId: 'socialapp-5270d',
    storageBucket: 'socialapp-5270d.firebasestorage.app',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4Gi3HehfGZK9ZewC0bcw0n9lh5fY7CEA',
    appId: '1:322956468011:web:79500fff32759e84792f6e',
    messagingSenderId: '322956468011',
    projectId: 'socialapp-5270d',
    authDomain: 'socialapp-5270d.firebaseapp.com',
    storageBucket: 'socialapp-5270d.firebasestorage.app',
    measurementId: 'G-7GB4D5TJDX',
  );
}
